name: Upload Ovadia Lambda to S3

on:
  push:
    branches:
      - main

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Zip Ovadia Lambda code
        run: |
          cd ovadia
          zip ../lambda.zip index.js

      - name: Upload lambda.zip to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl private --exact-timestamps --exclude '.git*'
        env:
          AWS_S3_BUCKET: mood-generator-lambda
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-2
          SOURCE_DIR: "./"
